apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-6
  namespace: go-app-6
  labels: 
    entity-id: go-app-6
    app: go-app-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-6
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: go-app-6
        entity-id: go-app-6
        app: go-app-6
    spec:
      serviceAccountName: go-app-6
      containers:
      - name: go-app-6
        # image: dgeorgievski/go-app-6:0.1.0
        image: dgeorgievski/go-app:0.1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"  
            cpu: "200m"       
          requests:
            memory: "128Mi"  
            cpu: "100m"      
